## Data Preprocessing for Adult Income Dataset

In [7]:
# Load the Adult Income dataset
try:
    # Assuming the 'adult.csv' file is available in the /content/ directory
    df_adult = pd.read_csv('/content/adult.csv')
    print("Adult Income dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'adult.csv' not found. Please ensure the file is uploaded to '/content/'.")
    df_adult = pd.DataFrame() # Create an empty DataFrame to avoid errors later

# Display the first 5 rows and basic information
if not df_adult.empty:
    print("\nFirst 5 rows of Adult Income dataset:")
    display(df_adult.head())
    print("\nInformation about Adult Income dataset:")
    df_adult.info()
    print("\nDescriptive statistics for Adult Income dataset:")
    display(df_adult.describe())

Adult Income dataset loaded successfully.

First 5 rows of Adult Income dataset:

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

Information about Adult Income dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

Descriptive statistics for Adult Income dataset:

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

### 1. Data Cleaning: Handling Missing Values (Adult Income Dataset)

In [8]:
if not df_adult.empty:
    # Missing values in this dataset are often represented as '?' or other placeholders.
    # First, replace these placeholders with NaN.
    df_adult_cleaned = df_adult.replace('?', np.nan).copy()

    print("Missing values in Adult Income dataset before handling:")
    display(df_adult_cleaned.isnull().sum())

    # Handle numerical missing values with the mean and categorical with the mode
    numerical_cols_adult = df_adult_cleaned.select_dtypes(include=np.number).columns.tolist()
    for col in numerical_cols_adult:
        if df_adult_cleaned[col].isnull().any():
            mean_val = df_adult_cleaned[col].mean()
            df_adult_cleaned[col].fillna(mean_val, inplace=True)
            print(f"Filled numerical missing values in '{col}' with mean: {mean_val:.2f}")

    categorical_cols_adult = df_adult_cleaned.select_dtypes(include='object').columns.tolist()
    for col in categorical_cols_adult:
        if df_adult_cleaned[col].isnull().any():
            # For categorical, it's safer to fill with the mode
            mode_val = df_adult_cleaned[col].mode()[0]
            df_adult_cleaned[col].fillna(mode_val, inplace=True)
            print(f"Filled categorical missing values in '{col}' with mode: {mode_val}")

    print("\nMissing values in Adult Income dataset after handling:")
    display(df_adult_cleaned.isnull().sum())
    print("\nFirst 5 rows after handling missing values:")
    display(df_adult_cleaned.head())

Missing values in Adult Income dataset before handling:

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

Filled categorical missing values in 'workclass' with mode: Private
Filled categorical missing values in 'occupation' with mode: Prof-specialty
Filled categorical missing values in 'native-country' with mode: United-States

Missing values in Adult Income dataset after handling:

/tmp/ipykernel_5707/3953077925.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_adult_cleaned[col].fillna(mode_val, inplace=True)

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

First 5 rows after handling missing values:

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,Private,103497,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,30,United-States,<=50K

### 2. Data Cleaning: Handling Categorical Data (Adult Income Dataset)

In [9]:
if not df_adult_cleaned.empty:
    categorical_cols_adult_encoding = df_adult_cleaned.select_dtypes(include='object').columns.tolist()

    if categorical_cols_adult_encoding:
        print(f"Categorical columns identified for encoding: {categorical_cols_adult_encoding}")
        # Apply one-hot encoding using pd.get_dummies
        df_adult_encoded = pd.get_dummies(df_adult_cleaned, columns=categorical_cols_adult_encoding, drop_first=True)
        print("\nDataset after one-hot encoding categorical features (first 5 rows):")
        display(df_adult_encoded.head())
    else:
        print("No categorical columns found for encoding in Adult Income dataset.")
        df_adult_encoded = df_adult_cleaned.copy()

    print("\nInformation after encoding categorical data:")
    df_adult_encoded.info()

Categorical columns identified for encoding: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country', 'income']

Dataset after one-hot encoding categorical features (first 5 rows):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_>50K
0,25,226802,7,0,0,40,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,38,89814,9,0,0,50,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,28,336951,12,0,0,40,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,44,160323,10,7688,0,40,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,18,103497,10,0,0,30,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

Information after encoding categorical data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 98 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   age                                        48842 non-null  int64
 1   fnlwgt                                     48842 non-null  int64
 2   educational-num                            48842 non-null  int64
 3   capital-gain                               48842 non-null  int64
 4   capital-loss                               48842 non-null  int64
 5   hours-per-week                             48842 non-null  int64
 6   workclass_Local-gov                        48842 non-null  bool
 7   workclass_Never-worked                     48842 non-null  bool
 8   workclass_Private                          48842 non-null  bool
 9   workclass_Self-emp-inc                     48842 non-null  bool
 10  workclass_Self-emp-not-inc                 48842 non-null  bool
 11  workclass_State-gov                        48842 non-null  bool
 12  workclass_Without-pay                      48842 non-null  bool
 13  education_11th                             48842 non-null  bool
 14  education_12th                             48842 non-null  bool
 15  education_1st-4th                          48842 non-null  bool
 16  education_5th-6th                          48842 non-null  bool
 17  education_7th-8th                          48842 non-null  bool
 18  education_9th                              48842 non-null  bool
 19  education_Assoc-acdm                       48842 non-null  bool
 20  education_Assoc-voc                        48842 non-null  bool
 21  education_Bachelors                        48842 non-null  bool
 22  education_Doctorate                        48842 non-null  bool
 23  education_HS-grad                          48842 non-null  bool
 24  education_Masters                          48842 non-null  bool
 25  education_Preschool                        48842 non-null  bool
 26  education_Prof-school                      48842 non-null  bool
 27  education_Some-college                     48842 non-null  bool
 28  marital-status_Married-AF-spouse           48842 non-null  bool
 29  marital-status_Married-civ-spouse          48842 non-null  bool
 30  marital-status_Married-spouse-absent       48842 non-null  bool
 31  marital-status_Never-married               48842 non-null  bool
 32  marital-status_Separated                   48842 non-null  bool
 33  marital-status_Widowed                     48842 non-null  bool
 34  occupation_Armed-Forces                    48842 non-null  bool
 35  occupation_Craft-repair                    48842 non-null  bool
 36  occupation_Exec-managerial                 48842 non-null  bool
 37  occupation_Farming-fishing                 48842 non-null  bool
 38  occupation_Handlers-cleaners               48842 non-null  bool
 39  occupation_Machine-op-inspct               48842 non-null  bool
 40  occupation_Other-service                   48842 non-null  bool
 41  occupation_Priv-house-serv                 48842 non-null  bool
 42  occupation_Prof-specialty                  48842 non-null  bool
 43  occupation_Protective-serv                 48842 non-null  bool
 44  occupation_Sales                           48842 non-null  bool
 45  occupation_Tech-support                    48842 non-null  bool
 46  occupation_Transport-moving                48842 non-null  bool
 47  relationship_Not-in-family                 48842 non-null  bool
 48  relationship_Other-relative                48842 non-null  bool
 49  relationship_Own-child                     48842 non-null  bool
 50  relationship_Unmarried                     48842 non-null  bool
 51  relationship_Wife                          48842 non-null  bool
 52  race_Asian-Pac-Islander                    48842 non-null  bool
 53  race_Black                                 48842 non-null  bool
 54  race_Other                                 48842 non-null  bool
 55  race_White                                 48842 non-null  bool
 56  gender_Male                                48842 non-null  bool
 57  native-country_Canada                      48842 non-null  bool
 58  native-country_China                       48842 non-null  bool
 59  native-country_Columbia                    48842 non-null  bool
 60  native-country_Cuba                        48842 non-null  bool
 61  native-country_Dominican-Republic          48842 non-null  bool
 62  native-country_Ecuador                     48842 non-null  bool
 63  native-country_El-Salvador                 48842 non-null  bool
 64  native-country_England                     48842 non-null  bool
 65  native-country_France                      48842 non-null  bool
 66  native-country_Germany                     48842 non-null  bool
 67  native-country_Greece                      48842 non-null  bool
 68  native-country_Guatemala                   48842 non-null  bool
 69  native-country_Haiti                       48842 non-null  bool
 70  native-country_Holand-Netherlands          48842 non-null  bool
 71  native-country_Honduras                    48842 non-null  bool
 72  native-country_Hong                        48842 non-null  bool
 73  native-country_Hungary                     48842 non-null  bool
 74  native-country_India                       48842 non-null  bool
 75  native-country_Iran                        48842 non-null  bool
 76  native-country_Ireland                     48842 non-null  bool
 77  native-country_Italy                       48842 non-null  bool
 78  native-country_Jamaica                     48842 non-null  bool
 79  native-country_Japan                       48842 non-null  bool
 80  native-country_Laos                        48842 non-null  bool
 81  native-country_Mexico                      48842 non-null  bool
 82  native-country_Nicaragua                   48842 non-null  bool
 83  native-country_Outlying-US(Guam-USVI-etc)  48842 non-null  bool
 84  native-country_Peru                        48842 non-null  bool
 85  native-country_Philippines                 48842 non-null  bool
 86  native-country_Poland                      48842 non-null  bool
 87  native-country_Portugal                    48842 non-null  bool
 88  native-country_Puerto-Rico                 48842 non-null  bool
 89  native-country_Scotland                    48842 non-null  bool
 90  native-country_South                       48842 non-null  bool
 91  native-country_Taiwan                      48842 non-null  bool
 92  native-country_Thailand                    48842 non-null  bool
 93  native-country_Trinadad&Tobago             48842 non-null  bool
 94  native-country_United-States               48842 non-null  bool
 95  native-country_Vietnam                     48842 non-null  bool
 96  native-country_Yugoslavia                  48842 non-null  bool
 97  income_>50K                                48842 non-null  bool
dtypes: bool(92), int64(6)
memory usage: 6.5 MB

### 3. Data Cleaning: Handling Outliers (Adult Income Dataset)

In [10]:
if 'df_adult_encoded' in locals() and not df_adult_encoded.empty:
    # We'll use the IQR (Interquartile Range) method to detect and handle outliers.
    # Numerical columns
    numerical_features_adult = df_adult_encoded.select_dtypes(include=np.number).columns.tolist()

    print("\nDetecting and handling outliers using IQR method for Adult Income dataset...")

    df_adult_outliers_handled = df_adult_encoded.copy()

    for column in numerical_features_adult:
        Q1 = df_adult_outliers_handled[column].quantile(0.25)
        Q3 = df_adult_outliers_handled[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Count outliers
        outliers_count = df_adult_outliers_handled[(df_adult_outliers_handled[column] < lower_bound) | (df_adult_outliers_handled[column] > upper_bound)].shape[0]
        if outliers_count > 0:
            print(f"Column '{column}': {outliers_count} outliers detected (below {lower_bound:.2f} or above {upper_bound:.2f})")
            # Capping outliers: replace values outside the bounds with the bounds themselves
            df_adult_outliers_handled[column] = np.where(df_adult_outliers_handled[column] < lower_bound, lower_bound, df_adult_outliers_handled[column])
            df_adult_outliers_handled[column] = np.where(df_adult_outliers_handled[column] > upper_bound, upper_bound, df_adult_outliers_handled[column])
            print(f"  Outliers in '{column}' have been capped.")
        else:
            print(f"Column '{column}': No significant outliers detected.")

    print("\nDescriptive statistics after outlier handling (Adult Income dataset):")
    display(df_adult_outliers_handled.describe())

Detecting and handling outliers using IQR method for Adult Income dataset...
Column 'age': 216 outliers detected (below -2.00 or above 78.00)
  Outliers in 'age' have been capped.
Column 'fnlwgt': 1453 outliers detected (below -62586.75 or above 417779.25)
  Outliers in 'fnlwgt' have been capped.
Column 'educational-num': 1794 outliers detected (below 4.50 or above 16.50)
  Outliers in 'educational-num' have been capped.
Column 'capital-gain': 4035 outliers detected (below 0.00 or above 0.00)
  Outliers in 'capital-gain' have been capped.
Column 'capital-loss': 2282 outliers detected (below 0.00 or above 0.00)
  Outliers in 'capital-loss' have been capped.
Column 'hours-per-week': 13496 outliers detected (below 32.50 or above 52.50)
  Outliers in 'hours-per-week' have been capped.

Descriptive statistics after outlier handling (Adult Income dataset):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,48842.000000,48842.000000,48842.0,48842.0,48842.000000
mean,38.618566,186770.707163,10.122088,0.0,0.0,41.192805
std,13.630359,95328.614282,2.456895,0.0,0.0,6.184799
min,17.000000,12285.000000,4.500000,0.0,0.0,32.500000
25%,28.000000,117550.500000,9.000000,0.0,0.0,40.000000
50%,37.000000,178144.500000,10.000000,0.0,0.0,40.000000
75%,48.000000,237642.000000,12.000000,0.0,0.0,45.000000
max,78.000000,417779.250000,16.000000,0.0,0.0,52.500000

### 4. Data Transformations: Min-Max Scaler (Normalization) (Adult Income Dataset)

In [11]:
if 'df_adult_outliers_handled' in locals() and not df_adult_outliers_handled.empty:
    # Initialize MinMaxScaler
    minmax_scaler_adult = MinMaxScaler()

    # Apply Min-Max Scaling to numerical features
    numerical_features_adult_scaled = df_adult_outliers_handled.select_dtypes(include=np.number).columns.tolist()

    df_adult_minmax_scaled = df_adult_outliers_handled.copy()
    df_adult_minmax_scaled[numerical_features_adult_scaled] = minmax_scaler_adult.fit_transform(df_adult_minmax_scaled[numerical_features_adult_scaled])

    print("\nAdult Income dataset after Min-Max Scaling (first 5 rows):")
    display(df_adult_minmax_scaled.head())
    print("\nDescriptive statistics after Min-Max Scaling (Adult Income dataset):")
    display(df_adult_minmax_scaled.describe())

Adult Income dataset after Min-Max Scaling (first 5 rows):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_>50K
0,0.131148,0.529026,0.217391,0.0,0.0,0.375,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,0.344262,0.191196,0.391304,0.0,0.0,0.875,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,0.180328,0.800667,0.652174,0.0,0.0,0.375,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0.442623,0.365080,0.478261,0.0,0.0,0.375,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,0.016393,0.224940,0.478261,0.0,0.0,0.000,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

Descriptive statistics after Min-Max Scaling (Adult Income dataset):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,48842.000000,48842.000000,48842.0,48842.0,48842.00000
mean,0.354403,0.430304,0.488877,0.0,0.0,0.43464
std,0.223449,0.235092,0.213643,0.0,0.0,0.30924
min,0.000000,0.000000,0.000000,0.0,0.0,0.00000
25%,0.180328,0.259598,0.391304,0.0,0.0,0.37500
50%,0.327869,0.409030,0.478261,0.0,0.0,0.37500
75%,0.508197,0.555759,0.652174,0.0,0.0,0.62500
max,1.000000,1.000000,1.000000,0.0,0.0,1.00000

### 5. Data Transformations: Standard Scaler (Adult Income Dataset)

In [12]:
if 'df_adult_outliers_handled' in locals() and not df_adult_outliers_handled.empty:
    # Initialize StandardScaler
    standard_scaler_adult = StandardScaler()

    # Apply Standard Scaling to numerical features
    # Using the same set of numerical features as for Min-Max Scaler
    numerical_features_adult_scaled = df_adult_outliers_handled.select_dtypes(include=np.number).columns.tolist()

    df_adult_standard_scaled = df_adult_outliers_handled.copy()
    df_adult_standard_scaled[numerical_features_adult_scaled] = standard_scaler_adult.fit_transform(df_adult_standard_scaled[numerical_features_adult_scaled])

    print("\nAdult Income dataset after Standard Scaling (first 5 rows):")
    display(df_adult_standard_scaled.head())
    print("\nDescriptive statistics after Standard Scaling (Adult Income dataset):")
    display(df_adult_standard_scaled.describe())

Adult Income dataset after Standard Scaling (first 5 rows):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_>50K
0,-0.999145,0.419934,-1.270758,0.0,0.0,-0.192863,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,-0.045382,-1.017089,-0.456714,0.0,0.0,1.424021,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,-0.779046,1.575412,0.764352,0.0,0.0,-0.192863,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0.394816,-0.277440,-0.049692,0.0,0.0,-0.192863,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,-1.512710,-0.873553,-0.049692,0.0,0.0,-1.405526,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

Descriptive statistics after Standard Scaling (Adult Income dataset):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,4.884200e+04,4.884200e+04,4.884200e+04,48842.0,48842.0,4.884200e+04
mean,2.219991e-16,1.600256e-17,-3.305256e-16,0.0,0.0,4.614556e-16
std,1.000010e+00,1.000010e+00,1.000010e+00,0.0,0.0,1.000010e+00
min,-1.586076e+00,-1.830379e+00,-2.288313e+00,0.0,0.0,-1.405526e+00
25%,-7.790458e-01,-7.261295e-01,-4.567143e-01,0.0,0.0,-1.928628e-01
50%,-1.187483e-01,-9.049010e-02,-4.969232e-02,0.0,0.0,-1.928628e-01
75%,6.882819e-01,5.336468e-01,7.643517e-01,0.0,0.0,6.155792e-01
max,2.889274e+00,2.423311e+00,2.392440e+00,0.0,0.0,1.828242e+00

## Data Preprocessing for Adult Income Dataset

In [13]:
# Load the Adult Income dataset
try:
    # Assuming the 'adult.csv' file is available in the /content/ directory
    df_adult = pd.read_csv('/content/adult.csv')
    print("Adult Income dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'adult.csv' not found. Please ensure the file is uploaded to '/content/'.")
    df_adult = pd.DataFrame() # Create an empty DataFrame to avoid errors later

# Display the first 5 rows and basic information
if not df_adult.empty:
    print("\nFirst 5 rows of Adult Income dataset:")
    display(df_adult.head())
    print("\nInformation about Adult Income dataset:")
    df_adult.info()
    print("\nDescriptive statistics for Adult Income dataset:")
    display(df_adult.describe())

Adult Income dataset loaded successfully.

First 5 rows of Adult Income dataset:

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

Information about Adult Income dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

Descriptive statistics for Adult Income dataset:

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

### 1. Data Cleaning: Handling Missing Values (Adult Income Dataset)

In [14]:
if not df_adult.empty:
    # Missing values in this dataset are often represented as '?' or other placeholders.
    # First, replace these placeholders with NaN.
    df_adult_cleaned = df_adult.replace('?', np.nan).copy()

    print("Missing values in Adult Income dataset before handling:")
    display(df_adult_cleaned.isnull().sum())

    # Handle numerical missing values with the mean and categorical with the mode
    numerical_cols_adult = df_adult_cleaned.select_dtypes(include=np.number).columns.tolist()
    for col in numerical_cols_adult:
        if df_adult_cleaned[col].isnull().any():
            mean_val = df_adult_cleaned[col].mean()
            df_adult_cleaned[col].fillna(mean_val, inplace=True)
            print(f"Filled numerical missing values in '{col}' with mean: {mean_val:.2f}")

    categorical_cols_adult = df_adult_cleaned.select_dtypes(include='object').columns.tolist()
    for col in categorical_cols_adult:
        if df_adult_cleaned[col].isnull().any():
            # For categorical, it's safer to fill with the mode
            mode_val = df_adult_cleaned[col].mode()[0]
            df_adult_cleaned[col].fillna(mode_val, inplace=True)
            print(f"Filled categorical missing values in '{col}' with mode: {mode_val}")

    print("\nMissing values in Adult Income dataset after handling:")
    display(df_adult_cleaned.isnull().sum())
    print("\nFirst 5 rows after handling missing values:")
    display(df_adult_cleaned.head())

Missing values in Adult Income dataset before handling:

age                   0
workclass          2799
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2809
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      857
income                0
dtype: int64

Filled categorical missing values in 'workclass' with mode: Private
Filled categorical missing values in 'occupation' with mode: Prof-specialty
Filled categorical missing values in 'native-country' with mode: United-States

Missing values in Adult Income dataset after handling:

/tmp/ipykernel_5707/3953077925.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_adult_cleaned[col].fillna(mode_val, inplace=True)

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

First 5 rows after handling missing values:

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,Private,103497,Some-college,10,Never-married,Prof-specialty,Own-child,White,Female,0,0,30,United-States,<=50K

### 2. Data Cleaning: Handling Categorical Data (Adult Income Dataset)

In [15]:
if not df_adult_cleaned.empty:
    categorical_cols_adult_encoding = df_adult_cleaned.select_dtypes(include='object').columns.tolist()

    if categorical_cols_adult_encoding:
        print(f"Categorical columns identified for encoding: {categorical_cols_adult_encoding}")
        # Apply one-hot encoding using pd.get_dummies
        df_adult_encoded = pd.get_dummies(df_adult_cleaned, columns=categorical_cols_adult_encoding, drop_first=True)
        print("\nDataset after one-hot encoding categorical features (first 5 rows):")
        display(df_adult_encoded.head())
    else:
        print("No categorical columns found for encoding in Adult Income dataset.")
        df_adult_encoded = df_adult_cleaned.copy()

    print("\nInformation after encoding categorical data:")
    df_adult_encoded.info()

Categorical columns identified for encoding: ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country', 'income']

Dataset after one-hot encoding categorical features (first 5 rows):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_>50K
0,25,226802,7,0,0,40,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,38,89814,9,0,0,50,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,28,336951,12,0,0,40,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,44,160323,10,7688,0,40,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,18,103497,10,0,0,30,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

Information after encoding categorical data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 98 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   age                                        48842 non-null  int64
 1   fnlwgt                                     48842 non-null  int64
 2   educational-num                            48842 non-null  int64
 3   capital-gain                               48842 non-null  int64
 4   capital-loss                               48842 non-null  int64
 5   hours-per-week                             48842 non-null  int64
 6   workclass_Local-gov                        48842 non-null  bool
 7   workclass_Never-worked                     48842 non-null  bool
 8   workclass_Private                          48842 non-null  bool
 9   workclass_Self-emp-inc                     48842 non-null  bool
 10  workclass_Self-emp-not-inc                 48842 non-null  bool
 11  workclass_State-gov                        48842 non-null  bool
 12  workclass_Without-pay                      48842 non-null  bool
 13  education_11th                             48842 non-null  bool
 14  education_12th                             48842 non-null  bool
 15  education_1st-4th                          48842 non-null  bool
 16  education_5th-6th                          48842 non-null  bool
 17  education_7th-8th                          48842 non-null  bool
 18  education_9th                              48842 non-null  bool
 19  education_Assoc-acdm                       48842 non-null  bool
 20  education_Assoc-voc                        48842 non-null  bool
 21  education_Bachelors                        48842 non-null  bool
 22  education_Doctorate                        48842 non-null  bool
 23  education_HS-grad                          48842 non-null  bool
 24  education_Masters                          48842 non-null  bool
 25  education_Preschool                        48842 non-null  bool
 26  education_Prof-school                      48842 non-null  bool
 27  education_Some-college                     48842 non-null  bool
 28  marital-status_Married-AF-spouse           48842 non-null  bool
 29  marital-status_Married-civ-spouse          48842 non-null  bool
 30  marital-status_Married-spouse-absent       48842 non-null  bool
 31  marital-status_Never-married               48842 non-null  bool
 32  marital-status_Separated                   48842 non-null  bool
 33  marital-status_Widowed                     48842 non-null  bool
 34  occupation_Armed-Forces                    48842 non-null  bool
 35  occupation_Craft-repair                    48842 non-null  bool
 36  occupation_Exec-managerial                 48842 non-null  bool
 37  occupation_Farming-fishing                 48842 non-null  bool
 38  occupation_Handlers-cleaners               48842 non-null  bool
 39  occupation_Machine-op-inspct               48842 non-null  bool
 40  occupation_Other-service                   48842 non-null  bool
 41  occupation_Priv-house-serv                 48842 non-null  bool
 42  occupation_Prof-specialty                  48842 non-null  bool
 43  occupation_Protective-serv                 48842 non-null  bool
 44  occupation_Sales                           48842 non-null  bool
 45  occupation_Tech-support                    48842 non-null  bool
 46  occupation_Transport-moving                48842 non-null  bool
 47  relationship_Not-in-family                 48842 non-null  bool
 48  relationship_Other-relative                48842 non-null  bool
 49  relationship_Own-child                     48842 non-null  bool
 50  relationship_Unmarried                     48842 non-null  bool
 51  relationship_Wife                          48842 non-null  bool
 52  race_Asian-Pac-Islander                    48842 non-null  bool
 53  race_Black                                 48842 non-null  bool
 54  race_Other                                 48842 non-null  bool
 55  race_White                                 48842 non-null  bool
 56  gender_Male                                48842 non-null  bool
 57  native-country_Canada                      48842 non-null  bool
 58  native-country_China                       48842 non-null  bool
 59  native-country_Columbia                    48842 non-null  bool
 60  native-country_Cuba                        48842 non-null  bool
 61  native-country_Dominican-Republic          48842 non-null  bool
 62  native-country_Ecuador                     48842 non-null  bool
 63  native-country_El-Salvador                 48842 non-null  bool
 64  native-country_England                     48842 non-null  bool
 65  native-country_France                      48842 non-null  bool
 66  native-country_Germany                     48842 non-null  bool
 67  native-country_Greece                      48842 non-null  bool
 68  native-country_Guatemala                   48842 non-null  bool
 69  native-country_Haiti                       48842 non-null  bool
 70  native-country_Holand-Netherlands          48842 non-null  bool
 71  native-country_Honduras                    48842 non-null  bool
 72  native-country_Hong                        48842 non-null  bool
 73  native-country_Hungary                     48842 non-null  bool
 74  native-country_India                       48842 non-null  bool
 75  native-country_Iran                        48842 non-null  bool
 76  native-country_Ireland                     48842 non-null  bool
 77  native-country_Italy                       48842 non-null  bool
 78  native-country_Jamaica                     48842 non-null  bool
 79  native-country_Japan                       48842 non-null  bool
 80  native-country_Laos                        48842 non-null  bool
 81  native-country_Mexico                      48842 non-null  bool
 82  native-country_Nicaragua                   48842 non-null  bool
 83  native-country_Outlying-US(Guam-USVI-etc)  48842 non-null  bool
 84  native-country_Peru                        48842 non-null  bool
 85  native-country_Philippines                 48842 non-null  bool
 86  native-country_Poland                      48842 non-null  bool
 87  native-country_Portugal                    48842 non-null  bool
 88  native-country_Puerto-Rico                 48842 non-null  bool
 89  native-country_Scotland                    48842 non-null  bool
 90  native-country_South                       48842 non-null  bool
 91  native-country_Taiwan                      48842 non-null  bool
 92  native-country_Thailand                    48842 non-null  bool
 93  native-country_Trinadad&Tobago             48842 non-null  bool
 94  native-country_United-States               48842 non-null  bool
 95  native-country_Vietnam                     48842 non-null  bool
 96  native-country_Yugoslavia                  48842 non-null  bool
 97  income_>50K                                48842 non-null  bool
dtypes: bool(92), int64(6)
memory usage: 6.5 MB

### 3. Data Cleaning: Handling Outliers (Adult Income Dataset)

In [16]:
if 'df_adult_encoded' in locals() and not df_adult_encoded.empty:
    # We'll use the IQR (Interquartile Range) method to detect and handle outliers.
    # Numerical columns
    numerical_features_adult = df_adult_encoded.select_dtypes(include=np.number).columns.tolist()

    print("\nDetecting and handling outliers using IQR method for Adult Income dataset...")

    df_adult_outliers_handled = df_adult_encoded.copy()

    for column in numerical_features_adult:
        Q1 = df_adult_outliers_handled[column].quantile(0.25)
        Q3 = df_adult_outliers_handled[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Count outliers
        outliers_count = df_adult_outliers_handled[(df_adult_outliers_handled[column] < lower_bound) | (df_adult_outliers_handled[column] > upper_bound)].shape[0]
        if outliers_count > 0:
            print(f"Column '{column}': {outliers_count} outliers detected (below {lower_bound:.2f} or above {upper_bound:.2f})")
            # Capping outliers: replace values outside the bounds with the bounds themselves
            df_adult_outliers_handled[column] = np.where(df_adult_outliers_handled[column] < lower_bound, lower_bound, df_adult_outliers_handled[column])
            df_adult_outliers_handled[column] = np.where(df_adult_outliers_handled[column] > upper_bound, upper_bound, df_adult_outliers_handled[column])
            print(f"  Outliers in '{column}' have been capped.")
        else:
            print(f"Column '{column}': No significant outliers detected.")

    print("\nDescriptive statistics after outlier handling (Adult Income dataset):")
    display(df_adult_outliers_handled.describe())

Detecting and handling outliers using IQR method for Adult Income dataset...
Column 'age': 216 outliers detected (below -2.00 or above 78.00)
  Outliers in 'age' have been capped.
Column 'fnlwgt': 1453 outliers detected (below -62586.75 or above 417779.25)
  Outliers in 'fnlwgt' have been capped.
Column 'educational-num': 1794 outliers detected (below 4.50 or above 16.50)
  Outliers in 'educational-num' have been capped.
Column 'capital-gain': 4035 outliers detected (below 0.00 or above 0.00)
  Outliers in 'capital-gain' have been capped.
Column 'capital-loss': 2282 outliers detected (below 0.00 or above 0.00)
  Outliers in 'capital-loss' have been capped.
Column 'hours-per-week': 13496 outliers detected (below 32.50 or above 52.50)
  Outliers in 'hours-per-week' have been capped.

Descriptive statistics after outlier handling (Adult Income dataset):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,48842.000000,48842.000000,48842.0,48842.0,48842.000000
mean,38.618566,186770.707163,10.122088,0.0,0.0,41.192805
std,13.630359,95328.614282,2.456895,0.0,0.0,6.184799
min,17.000000,12285.000000,4.500000,0.0,0.0,32.500000
25%,28.000000,117550.500000,9.000000,0.0,0.0,40.000000
50%,37.000000,178144.500000,10.000000,0.0,0.0,40.000000
75%,48.000000,237642.000000,12.000000,0.0,0.0,45.000000
max,78.000000,417779.250000,16.000000,0.0,0.0,52.500000

### 4. Data Transformations: Min-Max Scaler (Normalization) (Adult Income Dataset)

In [17]:
if 'df_adult_outliers_handled' in locals() and not df_adult_outliers_handled.empty:
    # Initialize MinMaxScaler
    minmax_scaler_adult = MinMaxScaler()

    # Apply Min-Max Scaling to numerical features
    numerical_features_adult_scaled = df_adult_outliers_handled.select_dtypes(include=np.number).columns.tolist()

    df_adult_minmax_scaled = df_adult_outliers_handled.copy()
    df_adult_minmax_scaled[numerical_features_adult_scaled] = minmax_scaler_adult.fit_transform(df_adult_minmax_scaled[numerical_features_adult_scaled])

    print("\nAdult Income dataset after Min-Max Scaling (first 5 rows):")
    display(df_adult_minmax_scaled.head())
    print("\nDescriptive statistics after Min-Max Scaling (Adult Income dataset):")
    display(df_adult_minmax_scaled.describe())

Adult Income dataset after Min-Max Scaling (first 5 rows):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_>50K
0,0.131148,0.529026,0.217391,0.0,0.0,0.375,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,0.344262,0.191196,0.391304,0.0,0.0,0.875,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,0.180328,0.800667,0.652174,0.0,0.0,0.375,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0.442623,0.365080,0.478261,0.0,0.0,0.375,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,0.016393,0.224940,0.478261,0.0,0.0,0.000,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

Descriptive statistics after Min-Max Scaling (Adult Income dataset):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,48842.000000,48842.000000,48842.0,48842.0,48842.00000
mean,0.354403,0.430304,0.488877,0.0,0.0,0.43464
std,0.223449,0.235092,0.213643,0.0,0.0,0.30924
min,0.000000,0.000000,0.000000,0.0,0.0,0.00000
25%,0.180328,0.259598,0.391304,0.0,0.0,0.37500
50%,0.327869,0.409030,0.478261,0.0,0.0,0.37500
75%,0.508197,0.555759,0.652174,0.0,0.0,0.62500
max,1.000000,1.000000,1.000000,0.0,0.0,1.00000

### 5. Data Transformations: Standard Scaler (Adult Income Dataset)

In [18]:
if 'df_adult_outliers_handled' in locals() and not df_adult_outliers_handled.empty:
    # Initialize StandardScaler
    standard_scaler_adult = StandardScaler()

    # Apply Standard Scaling to numerical features
    # Using the same set of numerical features as for Min-Max Scaler
    numerical_features_adult_scaled = df_adult_outliers_handled.select_dtypes(include=np.number).columns.tolist()

    df_adult_standard_scaled = df_adult_outliers_handled.copy()
    df_adult_standard_scaled[numerical_features_adult_scaled] = standard_scaler_adult.fit_transform(df_adult_standard_scaled[numerical_features_adult_scaled])

    print("\nAdult Income dataset after Standard Scaling (first 5 rows):")
    display(df_adult_standard_scaled.head())
    print("\nDescriptive statistics after Standard Scaling (Adult Income dataset):")
    display(df_adult_standard_scaled.describe())

Adult Income dataset after Standard Scaling (first 5 rows):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,...,native-country_Puerto-Rico,native-country_Scotland,native-country_South,native-country_Taiwan,native-country_Thailand,native-country_Trinadad&Tobago,native-country_United-States,native-country_Vietnam,native-country_Yugoslavia,income_>50K
0,-0.999145,0.419934,-1.270758,0.0,0.0,-0.192863,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
1,-0.045382,-1.017089,-0.456714,0.0,0.0,1.424021,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
2,-0.779046,1.575412,0.764352,0.0,0.0,-0.192863,True,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0.394816,-0.277440,-0.049692,0.0,0.0,-0.192863,False,False,True,False,...,False,False,False,False,False,False,True,False,False,True
4,-1.512710,-0.873553,-0.049692,0.0,0.0,-1.405526,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False

Descriptive statistics after Standard Scaling (Adult Income dataset):

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,4.884200e+04,4.884200e+04,4.884200e+04,48842.0,48842.0,4.884200e+04
mean,2.219991e-16,1.600256e-17,-3.305256e-16,0.0,0.0,4.614556e-16
std,1.000010e+00,1.000010e+00,1.000010e+00,0.0,0.0,1.000010e+00
min,-1.586076e+00,-1.830379e+00,-2.288313e+00,0.0,0.0,-1.405526e+00
25%,-7.790458e-01,-7.261295e-01,-4.567143e-01,0.0,0.0,-1.928628e-01
50%,-1.187483e-01,-9.049010e-02,-4.969232e-02,0.0,0.0,-1.928628e-01
75%,6.882819e-01,5.336468e-01,7.643517e-01,0.0,0.0,6.155792e-01
max,2.889274e+00,2.423311e+00,2.392440e+00,0.0,0.0,1.828242e+00

## Data Preprocessing for Diabetes Dataset

In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

# Load the Diabetes dataset
try:
    df_diabetes = pd.read_csv('/content/Dataset of Diabetes  (1).csv')
    print("Diabetes dataset loaded successfully.")
except FileNotFoundError:
    print("Error: 'Dataset of Diabetes (1).csv' not found. Please ensure the file is uploaded to '/content/'.")
    df_diabetes = pd.DataFrame() # Create an empty DataFrame to avoid errors later

# Display the first 5 rows and basic information
if not df_diabetes.empty:
    print("\nFirst 5 rows of Diabetes dataset:")
    display(df_diabetes.head())
    print("\nInformation about Diabetes dataset:")
    df_diabetes.info()
    print("\nDescriptive statistics for Diabetes dataset:")
    display(df_diabetes.describe())

Diabetes dataset loaded successfully.

First 5 rows of Diabetes dataset:

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

Information about Diabetes dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   Gender     1000 non-null   object
 3   AGE        1000 non-null   int64
 4   Urea       1000 non-null   float64
 5   Cr         1000 non-null   int64
 6   HbA1c      1000 non-null   float64
 7   Chol       1000 non-null   float64
 8   TG         1000 non-null   float64
 9   HDL        1000 non-null   float64
 10  LDL        1000 non-null   float64
 11  VLDL       1000 non-null   float64
 12  BMI        1000 non-null   float64
 13  CLASS      1000 non-null   object
dtypes: float64(8), int64(4), object(2)
memory usage: 109.5+ KB

Descriptive statistics for Diabetes dataset:

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1.000000e+03,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,340.500000,2.705514e+05,53.528000,5.124743,68.943000,8.281160,4.862820,2.349610,1.204750,2.609790,1.854700,29.578020
std,240.397673,3.380758e+06,8.799241,2.935165,59.984747,2.534003,1.301738,1.401176,0.660414,1.115102,3.663599,4.962388
min,1.000000,1.230000e+02,20.000000,0.500000,6.000000,0.900000,0.000000,0.300000,0.200000,0.300000,0.100000,19.000000
25%,125.750000,2.406375e+04,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.700000,26.000000
50%,300.500000,3.439550e+04,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.900000,30.000000
75%,550.250000,4.538425e+04,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.500000,33.000000
max,800.000000,7.543566e+07,79.000000,38.900000,800.000000,16.000000,10.300000,13.800000,9.900000,9.900000,35.000000,47.750000

### 1. Data Cleaning: Handling Missing Values (Diabetes Dataset)

In [2]:
# Check for missing values
print("Missing values in Diabetes dataset before handling:")
display(df_diabetes.isnull().sum())

if not df_diabetes.empty:
    # Example strategy: Fill numerical missing values with the mean and categorical with the mode
    # For this dataset, 'Outcome' is the target, other columns are features.
    # Let's assume numerical features might have missing values. We'll fill with mean.

    # Identify numerical columns (excluding 'Outcome')
    numerical_cols = df_diabetes.select_dtypes(include=np.number).columns.tolist()
    if 'Outcome' in numerical_cols: # Assuming 'Outcome' is numerical (0 or 1)
        numerical_cols.remove('Outcome')

    for col in numerical_cols:
        if df_diabetes[col].isnull().any():
            mean_val = df_diabetes[col].mean()
            df_diabetes[col].fillna(mean_val, inplace=True)
            print(f"Filled missing values in '{col}' with mean: {mean_val:.2f}")

    # For any potential categorical columns, fill with mode (if any exist and have NaNs)
    categorical_cols = df_diabetes.select_dtypes(include='object').columns.tolist()
    for col in categorical_cols:
        if df_diabetes[col].isnull().any():
            mode_val = df_diabetes[col].mode()[0]
            df_diabetes[col].fillna(mode_val, inplace=True)
            print(f"Filled missing values in '{col}' with mode: {mode_val}")

    print("\nMissing values in Diabetes dataset after handling:")
    display(df_diabetes.isnull().sum())
    print("\nFirst 5 rows after handling missing values:")
    display(df_diabetes.head())

Missing values in Diabetes dataset before handling:

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

Missing values in Diabetes dataset after handling:

ID           0
No_Pation    0
Gender       0
AGE          0
Urea         0
Cr           0
HbA1c        0
Chol         0
TG           0
HDL          0
LDL          0
VLDL         0
BMI          0
CLASS        0
dtype: int64

First 5 rows after handling missing values:

,ID,No_Pation,Gender,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,CLASS
0,502,17975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
1,735,34221,M,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,N
2,420,47975,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
3,680,87656,F,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,N
4,504,34223,M,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,N

### 2. Data Cleaning: Handling Categorical Data (Diabetes Dataset)

In [3]:
if not df_diabetes.empty:
    # The Diabetes dataset typically contains only numerical features and a binary 'Outcome' (0 or 1).
    # If there were categorical features, we would use one-hot encoding or label encoding.
    # Let's identify if any columns were mistakenly read as 'object' type (indicating categorical).

    categorical_cols_diabetes = df_diabetes.select_dtypes(include='object').columns.tolist()

    if categorical_cols_diabetes:
        print(f"Categorical columns identified: {categorical_cols_diabetes}")
        # Apply one-hot encoding using pd.get_dummies
        df_diabetes = pd.get_dummies(df_diabetes, columns=categorical_cols_diabetes, drop_first=True)
        print("\nDataset after one-hot encoding categorical features:")
        display(df_diabetes.head())
    else:
        print("No categorical columns found in Diabetes dataset. All features are numerical or already encoded.")

    print("\nInformation after checking for categorical data:")
    df_diabetes.info()

Categorical columns identified: ['Gender', 'CLASS']

Dataset after one-hot encoding categorical features:

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_M,Gender_f,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,502,17975,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,False,False,False,False,False,False
1,735,34221,26,4.5,62,4.9,3.7,1.4,1.1,2.1,0.6,23.0,True,False,False,False,False,False
2,420,47975,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,False,False,False,False,False,False
3,680,87656,50,4.7,46,4.9,4.2,0.9,2.4,1.4,0.5,24.0,False,False,False,False,False,False
4,504,34223,33,7.1,46,4.9,4.9,1.0,0.8,2.0,0.4,21.0,True,False,False,False,False,False

Information after checking for categorical data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         1000 non-null   int64
 1   No_Pation  1000 non-null   int64
 2   AGE        1000 non-null   int64
 3   Urea       1000 non-null   float64
 4   Cr         1000 non-null   int64
 5   HbA1c      1000 non-null   float64
 6   Chol       1000 non-null   float64
 7   TG         1000 non-null   float64
 8   HDL        1000 non-null   float64
 9   LDL        1000 non-null   float64
 10  VLDL       1000 non-null   float64
 11  BMI        1000 non-null   float64
 12  Gender_M   1000 non-null   bool
 13  Gender_f   1000 non-null   bool
 14  CLASS_N    1000 non-null   bool
 15  CLASS_P    1000 non-null   bool
 16  CLASS_Y    1000 non-null   bool
 17  CLASS_Y    1000 non-null   bool
dtypes: bool(6), float64(8), int64(4)
memory usage: 99.7 KB

### 3. Data Cleaning: Handling Outliers (Diabetes Dataset)

In [4]:
if not df_diabetes.empty:
    # We'll use the IQR (Interquartile Range) method to detect and handle outliers.
    # Numerical columns (excluding the target 'Outcome')
    numerical_features_diabetes = df_diabetes.select_dtypes(include=np.number).columns.tolist()
    if 'Outcome' in numerical_features_diabetes:
        numerical_features_diabetes.remove('Outcome')

    print("\nDetecting and handling outliers using IQR method for Diabetes dataset...")

    for column in numerical_features_diabetes:
        Q1 = df_diabetes[column].quantile(0.25)
        Q3 = df_diabetes[column].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        # Count outliers
        outliers_count = df_diabetes[(df_diabetes[column] < lower_bound) | (df_diabetes[column] > upper_bound)].shape[0]
        if outliers_count > 0:
            print(f"Column '{column}': {outliers_count} outliers detected (below {lower_bound:.2f} or above {upper_bound:.2f})")
            # Capping outliers: replace values outside the bounds with the bounds themselves
            df_diabetes[column] = np.where(df_diabetes[column] < lower_bound, lower_bound, df_diabetes[column])
            df_diabetes[column] = np.where(df_diabetes[column] > upper_bound, upper_bound, df_diabetes[column])
            print(f"  Outliers in '{column}' have been capped.")
        else:
            print(f"Column '{column}': No significant outliers detected.")

    print("\nDescriptive statistics after outlier handling:")
    display(df_diabetes.describe())

Detecting and handling outliers using IQR method for Diabetes dataset...
Column 'ID': No significant outliers detected.
Column 'No_Pation': 107 outliers detected (below -7917.00 or above 77365.00)
  Outliers in 'No_Pation' have been capped.
Column 'AGE': 98 outliers detected (below 39.00 or above 71.00)
  Outliers in 'AGE' have been capped.
Column 'Urea': 65 outliers detected (below 0.70 or above 8.70)
  Outliers in 'Urea' have been capped.
Column 'Cr': 52 outliers detected (below 10.50 or above 110.50)
  Outliers in 'Cr' have been capped.
Column 'HbA1c': 6 outliers detected (below 0.95 or above 15.75)
  Outliers in 'HbA1c' have been capped.
Column 'Chol': 27 outliers detected (below 1.60 or above 8.00)
  Outliers in 'Chol' have been capped.
Column 'TG': 55 outliers detected (below -0.60 or above 5.00)
  Outliers in 'TG' have been capped.
Column 'HDL': 50 outliers detected (below 0.30 or above 1.90)
  Outliers in 'HDL' have been capped.
Column 'LDL': 11 outliers detected (below -0.45 or above 5.55)
  Outliers in 'LDL' have been capped.
Column 'VLDL': 74 outliers detected (below -0.50 or above 2.70)
  Outliers in 'VLDL' have been capped.
Column 'BMI': 3 outliers detected (below 15.50 or above 43.50)
  Outliers in 'BMI' have been capped.

Descriptive statistics after outlier handling:

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000
mean,340.500000,35934.455000,53.986000,4.826843,62.345000,8.280960,4.843420,2.280610,1.142250,2.591640,1.14040,29.566770
std,240.397673,19549.661069,7.363968,1.714231,20.297906,2.532224,1.210029,1.150887,0.348675,1.039511,0.62744,4.926358
min,1.000000,123.000000,39.000000,0.700000,10.500000,0.950000,1.600000,0.300000,0.300000,0.300000,0.10000,19.000000
25%,125.750000,24063.750000,51.000000,3.700000,48.000000,6.500000,4.000000,1.500000,0.900000,1.800000,0.70000,26.000000
50%,300.500000,34395.500000,55.000000,4.600000,60.000000,8.000000,4.800000,2.000000,1.100000,2.500000,0.90000,30.000000
75%,550.250000,45384.250000,59.000000,5.700000,73.000000,10.200000,5.600000,2.900000,1.300000,3.300000,1.50000,33.000000
max,800.000000,77365.000000,71.000000,8.700000,110.500000,15.750000,8.000000,5.000000,1.900000,5.550000,2.70000,43.500000

### 4. Data Transformations: Min-Max Scaler (Normalization) (Diabetes Dataset)

In [5]:
if not df_diabetes.empty:
    # Initialize MinMaxScaler
    minmax_scaler = MinMaxScaler()

    # Apply Min-Max Scaling to numerical features (excluding 'Outcome')
    numerical_features_diabetes_scaled = df_diabetes.select_dtypes(include=np.number).columns.tolist()
    if 'Outcome' in numerical_features_diabetes_scaled:
        numerical_features_diabetes_scaled.remove('Outcome')

    df_diabetes_minmax_scaled = df_diabetes.copy()
    df_diabetes_minmax_scaled[numerical_features_diabetes_scaled] = minmax_scaler.fit_transform(df_diabetes_minmax_scaled[numerical_features_diabetes_scaled])

    print("\nDiabetes dataset after Min-Max Scaling (first 5 rows):")
    display(df_diabetes_minmax_scaled.head())
    print("\nDescriptive statistics after Min-Max Scaling:")
    display(df_diabetes_minmax_scaled.describe())

Diabetes dataset after Min-Max Scaling (first 5 rows):

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_M,Gender_f,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,0.627034,0.231118,0.34375,0.500,0.355,0.266892,0.406250,0.127660,1.0000,0.209524,0.153846,0.204082,False,False,False,False,False,False
1,0.918648,0.441444,0.00000,0.475,0.515,0.266892,0.328125,0.234043,0.5000,0.342857,0.192308,0.163265,True,False,False,False,False,False
2,0.524406,0.619508,0.34375,0.500,0.355,0.266892,0.406250,0.127660,1.0000,0.209524,0.153846,0.204082,False,False,False,False,False,False
3,0.849812,1.000000,0.34375,0.500,0.355,0.266892,0.406250,0.127660,1.0000,0.209524,0.153846,0.204082,False,False,False,False,False,False
4,0.629537,0.441470,0.00000,0.800,0.355,0.266892,0.515625,0.148936,0.3125,0.323810,0.115385,0.081633,True,False,False,False,False,False

Descriptive statistics after Min-Max Scaling:

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,0.424906,0.463627,0.468313,0.515855,0.518450,0.495335,0.506784,0.421406,0.526406,0.436503,0.400154,0.431297
std,0.300873,0.253096,0.230124,0.214279,0.202979,0.171096,0.189067,0.244870,0.217922,0.198002,0.241323,0.201076
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.156133,0.309945,0.375000,0.375000,0.375000,0.375000,0.375000,0.255319,0.375000,0.285714,0.230769,0.285714
50%,0.374844,0.443703,0.500000,0.487500,0.495000,0.476351,0.500000,0.361702,0.500000,0.419048,0.307692,0.448980
75%,0.687422,0.585967,0.625000,0.625000,0.625000,0.625000,0.625000,0.553191,0.625000,0.571429,0.538462,0.571429
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

### 5. Data Transformations: Standard Scaler (Diabetes Dataset)

In [6]:
if not df_diabetes.empty:
    # Initialize StandardScaler
    standard_scaler = StandardScaler()

    # Apply Standard Scaling to numerical features (excluding 'Outcome')
    # Using the same set of numerical features as for Min-Max Scaler
    df_diabetes_standard_scaled = df_diabetes.copy()
    df_diabetes_standard_scaled[numerical_features_diabetes_scaled] = standard_scaler.fit_transform(df_diabetes_standard_scaled[numerical_features_diabetes_scaled])

    print("\nDiabetes dataset after Standard Scaling (first 5 rows):")
    display(df_diabetes_standard_scaled.head())
    print("\nDescriptive statistics after Standard Scaling:")
    display(df_diabetes_standard_scaled.describe())

Diabetes dataset after Standard Scaling (first 5 rows):

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI,Gender_M,Gender_f,CLASS_N,CLASS_P,CLASS_Y,CLASS_Y
0,0.672140,-0.919118,-0.541555,-0.074031,-0.805658,-1.335842,-0.532005,-1.200206,2.174317,-1.146921,-1.021165,-1.130562,False,False,False,False,False,False
1,1.641852,-0.087690,-2.036062,-0.190760,-0.017005,-1.335842,-0.945425,-0.765541,-0.121234,-0.473190,-0.861708,-1.333654,True,False,False,False,False,False
2,0.330868,0.616204,-0.541555,-0.074031,-0.805658,-1.335842,-0.532005,-1.200206,2.174317,-1.146921,-1.021165,-1.130562,False,False,False,False,False,False
3,1.412950,2.120307,-0.541555,-0.074031,-0.805658,-1.335842,-0.532005,-1.200206,2.174317,-1.146921,-1.021165,-1.130562,False,False,False,False,False,False
4,0.680463,-0.087588,-2.036062,1.326714,-0.805658,-1.335842,0.046783,-1.113273,-0.982065,-0.569437,-1.180623,-1.739836,True,False,False,False,False,False

Descriptive statistics after Standard Scaling:

,ID,No_Pation,AGE,Urea,Cr,HbA1c,Chol,TG,HDL,LDL,VLDL,BMI
count,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03,1.000000e+03
mean,7.105427e-18,-8.526513e-17,3.694822e-16,-1.847411e-16,5.151435e-17,-1.136868e-16,-5.684342e-17,-2.131628e-16,1.030287e-16,4.618528e-17,-8.526513e-17,-3.979039e-16
std,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00,1.000500e+00
min,-1.412950e+00,-1.832736e+00,-2.036062e+00,-2.408607e+00,-2.555482e+00,-2.896516e+00,-2.681788e+00,-1.721803e+00,-2.416784e+00,-2.205640e+00,-1.658995e+00,-2.146019e+00
25%,-8.937585e-01,-6.075115e-01,-4.056908e-01,-6.576751e-01,-7.070768e-01,-7.036703e-01,-6.973731e-01,-6.786076e-01,-6.951214e-01,-7.619317e-01,-7.022505e-01,-7.243799e-01
50%,-1.664742e-01,-7.875968e-02,1.377664e-01,-1.323955e-01,-1.155870e-01,-1.110094e-01,-3.590138e-02,-2.439427e-01,-1.212338e-01,-8.820097e-02,-3.833356e-01,8.798523e-02
75%,8.729492e-01,4.836157e-01,6.812236e-01,5.096128e-01,5.251937e-01,7.582267e-01,6.255704e-01,5.384542e-01,4.526539e-01,6.817770e-01,5.734089e-01,6.972591e-01
max,1.912373e+00,2.120307e+00,2.311595e+00,2.260545e+00,2.373599e+00,2.951072e+00,2.609986e+00,2.364047e+00,2.174317e+00,2.847340e+00,2.486898e+00,2.829717e+00